Repository Bram-Hub/LEGUP, pull requests merged in 2022-08, with the labels that each got.

#233 Fixes of LinkTent/Tree, NoTentForTree
  src/main/java/edu/rpi/legup/puzzle/treetent/rules/LinkTentCaseRule.java
  src/main/java/edu/rpi/legup/puzzle/treetent/rules/LinkTreeCaseRule.java
  src/main/java/edu/rpi/legup/puzzle/treetent/rules/NoTentForTreeContradictionRule.java
Labels: bug, tree tent

#242 Contribute to Legup link changed
  src/main/java/edu/rpi/legup/ui/HomePanel.java
  src/main/java/edu/rpi/legup/ui/ProofEditorPanel.java
Labels: ui

#237 Home panel prompts for file when appropriate
  src/main/java/edu/rpi/legup/ui/HomePanel.java
  src/main/java/edu/rpi/legup/ui/ProofEditorPanel.java
  src/main/java/edu/rpi/legup/ui/PuzzleEditorPanel.java
Labels: ui, puzzle editor

#252 Fixed visual bug when running jar file outside IntelliJ
  src/main/java/edu/rpi/legup/model/elements/Element.java
  src/main/java/edu/rpi/legup/model/rules/Rule.java
Labels: bug, ui, puzzle editor

#256 Puzzle editor selection cosmetic changes
  src/main/java/edu/rpi/legup/app/Config.java
  src/main/java/edu/rpi/legup/ui/CreatePuzzleDialog.java
  src/main/java/edu/rpi/legup/ui/PickGameDialog.java
  src/main/resources/edu/rpi/legup/legup/config
Labels: enhancement, puzzle editor

#246 Updated cosmetics and fixed visual bugs
  src/main/java/edu/rpi/legup/app/Config.java
  src/main/java/edu/rpi/legup/ui/CreatePuzzleDialog.java
  src/main/java/edu/rpi/legup/ui/DynamicView.java
  src/main/java/edu/rpi/legup/ui/DynamicViewType.java
  src/main/java/edu/rpi/legup/ui/HomePanel.java
  src/main/java/edu/rpi/legup/ui/PickGameDialog.java
  src/main/java/edu/rpi/legup/ui/ProofEditorPanel.java
  src/main/java/edu/rpi/legup/ui/PuzzleEditorPanel.java
  src/main/java/edu/rpi/legup/ui/proofeditorui/treeview/TreePanel.java
  src/main/java/edu/rpi/legup/ui/proofeditorui/treeview/TreeView.java
  src/main/resources/edu/rpi/legup/images/Legup/LegupSplash.png
  src/main/resources/edu/rpi/legup/images/Legup/homepanel/Check All.png
  src/main/resources/edu/rpi/legup/legup/config
Labels: bug, ui

#261 Updated README.md and CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
  contributing.md
Labels: documentation
